name: Create release

on:
  push:
    branches:
      - 'release'
    paths:
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.export.outputs.exists }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: pnpm

      - name: get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: check tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: v${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: check pre-release
        id: pre-release
        run: |
          if [[ "${{ steps.package-version.outputs.current-version }}" =~ (alpha|beta|rc) ]]; then
            echo "pre=true" >> $GITHUB_OUTPUT
          else
            echo "pre=false" >> $GITHUB_OUTPUT
          fi

      - name: pnpm install
        if: steps.check-tag.outputs.exists == 'false'
        run: pnpm install --frozen-lockfile

      - name: create artifact
        if: steps.check-tag.outputs.exists == 'false'
        run: pnpm run build

      - name: archive artifact
        if: steps.check-tag.outputs.exists == 'false'
        run: zip -rj better-japanese.zip ./build

      - name: copy web artifact
        if: steps.check-tag.outputs.exists == 'false'
        run: cp ./src/web-embed/* ./

      - name: create release
        if: steps.check-tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.package-version.outputs.current-version }}
          tag_name: v${{ steps.package-version.outputs.current-version }}
          prerelease: ${{ steps.pre-release.outputs.pre }}
          files: |
            better-japanese.zip
            JA.js

      - name: export variable
        id: export
        run: echo "exists=${{ steps.check-tag.outputs.exists }}" >> $GITHUB_OUTPUT

  publish:
    needs: build
    if: needs.build.outputs.exists == 'false'
    uses: hideki0403/better-japanese/.github/workflows/publish.yml@release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}